### ISSUE TITLE
Unexpectedly seems to be prompting for CPAN configuration

### ISSUE THREAD

**Issue by neilb** [kevindawson/App-Midgen#2]
As suggested by the doc, I ran midgen in the top directory of one of my dists. But I got the following output. As you can see, I ctrl-c'd, because
- It's not being made clear why CPAN config is needed
- I don't install modules as the user I'm currently logged in as

The documentation should make clear that this might happen, and why, and interactively it should also be clearer, and there should be a command-line option to suppress this behaviour (or to exit, if appropriate).

Running midgen v0.12
Sorry, we have to rerun the configuration dialog for CPAN.pm due to
some missing parameters. Configuration will be written to
 <</Users/neilb/.cpan/CPAN/MyConfig.pm>>

CPAN.pm requires configuration, but most of it can be done automatically.
If you answer 'no' below, you will enter an interactive dialog for each
configuration option instead.

Would you like to configure as much as possible automatically? [yes] ^C

**Comment by kevindawson** [comment]
The current POD -> https://metacpan.org/module/App::Midgen#WARNINGS

but I will add more more as per your suggestion, thanks

Also will add a cmd line option to negate doing a cpan upgrade, as per your suggestion. I had considered it, but i am now convinced.

Thanks again for the critique

**Comment by neilb** [comment]
Ah, in the class doc but not the script. Sorry, should have dug a bit deeper.

A further suggestion: that WARNINGS section still doesn't say _why_ a link to CPAN is needed. I have all the dependent modules for my dist installed. I'm guessing that rather than parse the source you're looking for the metadata files in the dists, and you get that by downloading the modules using CPAN?

If so, it might be (a) a good idea to describe this in the doc, and (b) tell users this explictly when they're suddenly being prompted to configure CPAN :-)

Cheers

**Comment by kevindawson** [comment]
WARNINGS

As our mantra is to show the current version of a module, we do this by asking your local CPAN config for the information. Start-up may be slow as we request a CPAN reload index, against http://www.cpan.org/, or one of it's mirrors.

If you wish to skip this use option --...

 midgen --...

**Comment by kevindawson** [comment]
I have not decided what I will call ... yet :)

**Comment by neilb** [comment]
You say "show the current version of a module": do you mean the version installed locally, or the latest version that's on CPAN? If the latter, then you could use the MetaCPAN API to get that. If you're not familiar with that, I can give you some code I've got that shows how to get the latest version of a module from MetaCPAN.

**Comment by kevindawson** [comment]
working to my 'mission statement' :) ( even techies are allowed to pontificate ) 

_Food for thought, if we update our Modules, don't we want our users to use the current version, so should we not by default do the same with others Modules._

"or the latest version that's on CPAN?" yes

I would have thought that local CPAN would be faster than MetaCPAN, and if a 'reload index' has been performed only hours behind.

I had the model in the back of my mind that this should work against a local CPAN mirror, with no direct Internet access.

BUT, there is always a but :)

I am starting to think along the lines of 

 midgen --...

being a switch.

thanks to your kicking.

default -> local cpan + reload index

other -> make use of MetaCPAN API

so with that thought, I will say yes to your kind offer of a code snippet, thanks

**Comment by kevindawson** [comment]
switch to MetaCPAN

commented out CPAN config

see tag 0.13_01
