### ISSUE TITLE
Shipping MYMETA on CPAN

### ISSUE THREAD

**Issue by mbeijen** [kevindawson/App-Midgen#4]
Hi,

I found you include MYMETA.yml and MYMETA.json in your CPAN tarball. I'm not sure how you do that, if I run 'make dist' on App::Midgen the tarball does not have those files.

See also http://weblog.bulknews.net/post/44251476706/stop-shipping-mymeta-to-cpan

**Comment by kevindawson** [comment]
Thanks for the info.

I will fix in next release

have added \bMYMETA\* to MANIFEST.SKIP

Thanks for the critique

**Comment by kevindawson** [comment]
fixed and out:

http://cpan.metacpan.org/authors/id/B/BO/BOWTIE/App-Midgen-0.24.tar.gz
