### ISSUE TITLE
midgen reports modules loaded through Test::Requires as being required

### ISSUE THREAD

**Issue by tobyink** [kevindawson/App-Midgen#5]
If a module is loaded in a test like:

``` perl
use Test::Requires { "Moose" => "2.0000" };
```

I would _not_ expect "Moose" to show up in the dependency list generated. (That's the whole point of the Test::Requires module - it says that this particular test case requires Moose, but cleanly skips the test case if it's not available.)

For completeness, the following should also not result in a dependency on Moose/Moose::Role...

``` perl
use Test::Requires { "Moose" => "2.000" };
use Moose;
```

and...

``` perl
use Test::Requires { "Moose" => "2.000" };
use Moose::Role;
```

**Comment by kevindawson** [comment]
toby, thanks for the critique,

can you give me the dist name on CPAN an I will take a closer look, also the midgen [options used]

I would expect the META.json would look like

``` json
   "prereqs" : {
      "test" : {
         "suggests" : {
            "Moose" : "2.000"
         }
      }
   }
```

**Comment by tobyink** [comment]
I've been testing on Type-Tiny-0.016, in the root directory of the distribution, running midgen with no command-line options.

**Comment by kevindawson** [comment]
This is what I did, I made a dir called toby :)
with a single dir called t
then copied each of the following in turn

``` text
 | Moose                                    | 0        | /t/coercion-classy.t                           |
 | Moose                                    | 0        | /t/moose-coercion.t                            |
 | Moose                                    | 0        | /t/moose-autott.t                              |
 | Moose                                    | 0        | /t/moose.t                                     |
 | Moose                                    | 0        | /t/dwim-moose.t                                |
 | Moose                                    | 0        | /t/dwim-moose.t                                |
 | Moose                                    | 0        | /t/02-api.t                                    |
```

This first issue is the one that concerns me as it is outside of midgen in Perl::PrereqScanner it's
scan_prereqs --combine
/t/02-api.t
my $HAVE_MOOSE = eval { require Moose };
hence test required
midgen Eval scanner don't do eval Blocks yet :(

midgen Test::Requires is failing to find Moose
t/coercion-classy.t
use Test::Requires { Moose => 2.00 };

this is out of scope - bare word
see https://metacpan.org/module/Test::Requires
also see http://kevindawson.github.io/bowtie/2013/05/09/app-midgen-005/
change to
use Test::Requires { "Moose" => 2.00 };
recommends Moose 2.0802

midgen
t/dwim-moose.t 
use Test::Requires { "Moose" => "2.0600" };
use Test::Requires { "MooseX::Types" => "0.35" };
found
recommends Moose         2.0802
recommends MooseX::Types 0.36

t/moose-autott.t
bare word as above

t/moose-coercion.t
bare word as above

t/moose.t
bare word as above

**Comment by kevindawson** [comment]
need to add the following format to Eval scanner 

my $HAVE_MOOSE = eval { require Moose };

PPI:

``` perl
PPI::Document
  PPI::Statement::Variable
    PPI::Token::Word    'my'
    PPI::Token::Whitespace      ' '
    PPI::Token::Symbol      '$HAVE_MOOSE'
    PPI::Token::Whitespace      ' '
    PPI::Token::Operator    '='
    PPI::Token::Whitespace      ' '
    PPI::Token::Word    'eval'
    PPI::Token::Whitespace      ' '
    PPI::Structure::Block   { ... }
      PPI::Token::Whitespace    ' '
      PPI::Statement::Include
        PPI::Token::Word    'require'
        PPI::Token::Whitespace      ' '
        PPI::Token::Word    'Moose'
      PPI::Token::Whitespace    ' '
    PPI::Token::Structure   ';'
  PPI::Token::Whitespace    '\n'
```

I will add to P-PS Eval scanner test, what fun

**Comment by kevindawson** [comment]
toby, 

if you want to see what midgen is doing

try midgen -d 

against a single file, as in above

testdir/t/test.t
cd testdir
midgen -d

**Comment by kevindawson** [comment]
fixed in commit 35f8d6f
just hacked in eval scanner take four ( as in proposed for p-ps)
which now supports, both the following
eval { require Moose };
my $HAVE_MOOSE = eval { require Moose };

**Comment by kevindawson** [comment]
see tag 0.27_08 will push to cpan soon

suggest you try running 

midgen -f mi

the mi is the closest to MI-rdf

I you want an RDF output formay let me know

also take a look at

midgen -f infile

it might be of some use, I still have to document it

**Comment by kevindawson** [comment]
https://metacpan.org/release/BOWTIE/App-Midgen-0.25_08

hence closing

**Comment by kevindawson** [comment]
https://metacpan.org/release/BOWTIE/App-Midgen-0.25_09

added support for bare-words in test-requires scanner
