### ISSUE TITLE
MetaCPAN::API is deprecated, please use MetaCPAN::Client

### ISSUE THREAD

**Issue by mickeyn** [kevindawson/App-Midgen#7]
hi,
MetaCPAN::API is no longer maintained and we released a successor: MetaCPAN::Client which is an official client for MetaCPAN.
cheers,
Mickey

**Comment by kevindawson** [comment]
mickeyn

thanks for the update

I will branch and have a look

expect some Q's :)

**Comment by mickeyn** [comment]
sure thing, will be happy to assist.
cheers.

**Comment by kevindawson** [comment]
working solution in branch mcc 49697f5

requires current MetaCPAN::Client github to work, ie numeric support in module names

**Comment by mickeyn** [comment]
Sawyer will release a new version of the github code hopefully this week.

**Comment by xsawyerx** [comment]
Released.

**Comment by kevindawson** [comment]
Fixed in v0.34
Now available on CPAN

**Comment by xsawyerx** [comment]
@kevindawson++

**Comment by mickeyn** [comment]
cool! thanks ;)
